In [2]:
import numpy as np
d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(d))
print("sum of rows = ",np.sum(d, axis = 0))
print("sum of coloumn = ",np.sum(d, axis = 1))

45
sum of rows =  [12 15 18]
sum of coloumn =  [ 6 15 24]


In [3]:
print(d[0:2,2])

[3 6]


In [4]:
f = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])#2 X 3 X 3
print(f,np.shape(f))
print(f[0,1,1])
print(f[:,:,0])
print(f[0,0:,1:])
print(f[:,0,:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3)
5
[[ 1  4]
 [ 7 10]]
[[2 3]
 [5 6]]
[[1 2 3]
 [7 8 9]]
