In [5]:
#operation
import numpy as np
d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(d[2][2]) #indexing
print(np.ndim(d))
print(np.shape(d))
flattened = d.flatten()
print(flattened)
reshape = d.reshape(6,2)
print(reshape)

9
2
(4, 3)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [6]:
#fancy indexing
d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
idx = [[1,2], [2,2],[3,2]]
e = np.array([1,2,3,4,5,6])
ind = [1,4,3]
print(e[ind])
print(d[idx])

[2 5 4]
[[[ 4  5  6]
  [ 7  8  9]]

 [[ 7  8  9]
  [ 7  8  9]]

 [[10 11 12]
  [ 7  8  9]]]


In [8]:
#bollean indexing
e = np.array([1,2,3,4,5,6])
print(e[e % 2 == 0])
print(e[e >3])

[2 4 6]
[4 5 6]


In [9]:
#slicing
print(e[1:4])
print(e[1:5:2])
print(e[:])
print(e[::-1])

[2 3 4]
[2 4]
[1 2 3 4 5 6]
[6 5 4 3 2 1]
