In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5, "sumit"])
c = [1,2,3,4,5]
print(a,a.dtype,a.shape)
print(c,type(c))
print(b)

[1 2 3 4 5] int64 (5,)
[1, 2, 3, 4, 5] <class 'list'>
['1' '2' '3' '4' '5' 'sumit']


In [4]:
d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(d,d.dtype,d.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] int64 (4, 3)


In [18]:
#create
arr1 = np.zeros((3,4), "int64") #prefil
print(arr1,arr1.dtype,arr1.shape)
arr2 = np.ones((3,5)) #prefil
print(arr2,arr2.dtype,arr2.shape)
arr3 = np.full((3,4), 4 ) #prefil with val
print(arr3,arr3.dtype,arr3.shape)
arr4 = np.eye(3) #identity matrix
print(arr4,arr4.dtype,arr4.shape)
arr5 = np.arange(1,10,2) #range elements
print(arr5,arr5.dtype,arr5.shape)
arr6 = np.linspace(1,100, 4) # evenly range elements
print(arr6,arr6.dtype,arr6.shape)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] int64 (3, 4)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] float64 (3, 5)
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]] int64 (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] float64 (3, 3)
[1 3 5 7 9] int64 (5,)
[  1.  34.  67. 100.] float64 (4,)


In [27]:
#properties
d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(d.shape)
print(d.ndim)
print(d.size)
print(d.dtype)
flattened = d.flatten()
print(flattened)
reshape = d.reshape(6,2)
print(reshape)
float_e = d.astype(np.float64)
print(float_e,float_e.dtype)

(4, 3)
2
12
int64
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]] float64
